# This hash syntax requires ruby 2.4, haven't tried ruby 2.3 yet
SUBJECT_ETHNICITIES = { 'american_indian_alaska_native' => 'American Indian/Alaska Native',
                      'asian' => 'Asian',
                      'native_hawaiian_other_pacific_islander' => 'Native Hawaiian or Other Pacific Islander',
                      'black_african_american' => 'Black or African American',
                      'white' => 'white',
                      'more_than_one_race' => 'More than one race'}
SUBJECT_GENDERS = { 'male': 'Male',
                  'female': 'Female',
                  'other': 'Other' }
COLLEGES = { "Administration": "administration",
            "College of Dental Medicine": "college_of_dental_medicine",
            "College of Graduate Studies": "college_of_graduate_studies",
            "College of Health Professions": "college_of_health_professions",
            "College of Medicine": "college_of_medicine",
            "College of Nursing": "college_of_nursing",
            "College of Pharmacy": "college_of_pharmacy",
            "Other": "other",
            "Not MUSC Personnel": "not_musc_personnel" }

DEPARTMENTS = {
'Accounting': 'Accounting',
'Administration Support Service': 'Administration Support Service',
'Adult and Gerontology': 'Adult and Gerontology',
'Aerospace Studies': 'Aerospace Studies',
'African American Studies': 'African American Studies',
'American Studies': 'American Studies',
'Anatomy and Cell Biology': 'Anatomy and Cell Biology',
'Anesthesia': 'Anesthesia',
'Animal Care Unit': 'Animal Care Unit',
'Anthropology': 'Anthropology',
'Art and Art History': 'Art and Art History',
'Asian and Slavic Lang. and Lit': 'Asian and Slavic Lang. and Lit',
'Biocatalysis Bioprocessing Ctr': 'Biocatalysis Bioprocessing Ctr',
'Biochemistry': 'Biochemistry',
'Bioengineering': 'Bioengineering',
'Biology': 'Biology',
'Biomedical Engineering': 'Biomedical Engineering',
'Biostatistics': 'Biostatistics',
'Bus Admin College': 'Bus Admin College',
'Bus Admin Graduate Programs': 'Bus Admin Graduate Programs',
'Bus Admin Undergrad': 'Bus Admin Undergrad',
'Bus Centers and Institutes': 'Bus Centers and Institutes',
'Business Admin Research': 'Business Admin Research',
'Cad Research Engineering': 'Cad Research Engineering',
'Cancer Center': 'Cancer Center',
'Cardiothoracic Surgery': 'Cardiothoracic Surgery',
'Cardiovascular Center': 'Cardiovascular Center',
'CCOM Central Control': 'CCOM Central Control',
'Cent Elect Microscopy Facility': 'Cent Elect Microscopy Facility',
'Center For Muscular Dystrophy': 'Center For Muscular Dystrophy',
'Center For The Book': 'Center For The Book',
'Center On Aging': 'Center On Aging',
'Central Admin Facilities': 'Central Admin Facilities',
'Chemical and Biochem Engineer': 'Chemical and Biochem Engineer',
'Chemistry': 'Chemistry',
'Cinematic Arts': 'Cinematic Arts',
'Civil Environmental Engineer': 'Civil Environmental Engineer',
'Classics': 'Classics',
'Clinical Pastoral Care': 'Clinical Pastoral Care',
'Clinical Research Center': 'Clinical Research Center',
'Communication Sciences Disordr': 'Communication Sciences Disordr',
'Communication Studies': 'Communication Studies',
'Community and Behavioral Hlth': 'Community and Behavioral Hlth',
'Computer Science': 'Computer Science',
'Connie Belin Natl Center Educ': 'Connie Belin Natl Center Educ',
'Consultation and Res Med Educ': 'Consultation and Res Med Educ',
'Continuing Education Medicine': 'Continuing Education Medicine',
'Continuing Education Pharmacy': 'Continuing Education Pharmacy',
'CranioFACial Anomalie Rsch Ctr': 'CranioFACial Anomalie Rsch Ctr',
'Creative Media Group': 'Creative Media Group',
'Creative Writing': 'Creative Writing',
'Ctr Bioinformatic Comp Biology': 'Ctr Bioinformatic Comp Biology',
'Ctr For Adv Study In Meas and': 'Ctr For Adv Study In Meas and',
'Ctr for Health Policy and Res': 'Ctr for Health Policy and Res',
'Ctr for Public Health Practice': 'Ctr for Public Health Practice',
'Ctr for Public Health Stats': 'Ctr for Public Health Stats',
'Ctr for Stats Genetics Res': 'Ctr for Stats Genetics Res',
'Ctr Hlth Effect Of Environment': 'Ctr Hlth Effect Of Environment',
'Dance': 'Dance',
'DCE Courses and Workshops': 'DCE Courses and Workshops',
'Dental Clinic Administration': 'Dental Clinic Administration',
'Dentistry Administration': 'Dentistry Administration',
'Department Emergency Medicine': 'Department Emergency Medicine',
'Dermatology': 'Dermatology',
'Diabetes Research Center': 'Diabetes Research Center',
'Div of World Languages WLLC': 'Div of World Languages WLLC',
'Division Continuing Education': 'Division Continuing Education',
'Division Drug Information Svc': 'Division Drug Information Svc',
'Division Of Performing Arts': 'Division Of Performing Arts',
'Division Of Sponsored Programs': 'Division Of Sponsored Programs',
'Dows Institute Research': 'Dows Institute Research',
'Earth & Environmental Sciences': 'Earth & Environmental Sciences',
'Economics': 'Economics',
'Educ Policy Leadership Studies': 'Educ Policy Leadership Studies',
'Educ Teacher Leader Center': 'Educ Teacher Leader Center',
'Education Administration': 'Education Administration',
'Educational Placement': 'Educational Placement',
'Electrical Computer Engineer': 'Electrical Computer Engineer',
'Endodontics': 'Endodontics',
'Engineering Admin Ge': 'Engineering Admin Ge',
'Engineering Computer Network': 'Engineering Computer Network',
'Engineering Electronics Shop': 'Engineering Electronics Shop',
'Engineering Mechanical Shop': 'Engineering Mechanical Shop',
'English': 'English',
'Environmental Health & Safety': 'Environmental Health & Safety',
'Epidemiology': 'Epidemiology',
'ESL': 'ESL',
'Ethnic Inclusion': 'Ethnic Inclusion',
'Evaluation and Assessment Ctr': 'Evaluation and Assessment Ctr',
'Faculty Practice Admin': 'Faculty Practice Admin',
'Faculty Research Assistants': 'Faculty Research Assistants',
'Family Dentistry': 'Family Dentistry',
'Family Medicine': 'Family Medicine',
'Finance': 'Finance',
'French and Italian': 'French and Italian',
"Gender, Women's and Sexuality": 'Gender, Women''s and Sexuality',
'General University College': 'General University College',
'Geographic & Sustnablty Scienc': 'Geographic & Sustnablty Scienc',
'German': 'German',
'Global Region Environ Res Ctr': 'Global Region Environ Res Ctr',
'Grad College Operations Distr': 'Grad College Operations Distr',
'Graduate College Admin and Gen': 'Graduate College Admin and Gen',
'Graduate Student Aid Support': 'Graduate Student Aid Support',
'Health and Human Physiology': 'Health and Human Physiology',
'Health and Sports Studies': 'Health and Sports Studies',
'Health Management and Policy': 'Health Management and Policy',
'Heart & Vascular Center': 'Heart & Vascular Center',
'High Field NMR Facility': 'High Field NMR Facility',
'High Res Mass Spect Facility': 'High Res Mass Spect Facility',
'High Throughput Screen Facilty': 'High Throughput Screen Facilty',
'History': 'History',
'Honors Program': 'Honors Program',
'Hospital Based Programs': 'Hospital Based Programs',
'Hospital Dentistry': 'Hospital Dentistry',
'Hubbard Program': 'Hubbard Program',
'Human Subjects/IRB Office': 'Human Subjects/IRB Office',
'IA Consortium Substance Abuse': 'IA Consortium Substance Abuse',
'IDGP in Informatics': 'IDGP in Informatics',
'IIHR Hydroscience Engineering': 'IIHR Hydroscience Engineering',
'IMRF': 'IMRF',
'Industrial Engineering': 'Industrial Engineering',
'Institute Clin and Trans Scien': 'Institute Clin and Trans Scien',
'Institute Clinical Research': 'Institute Clinical Research',
'Institute for Human Genetics': 'Institute for Human Genetics',
'Inter Departmental Units': 'Inter Departmental Units',
'Interdepartmental Programs': 'Interdepartmental Programs',
'Interdepartmental Progs': 'Interdepartmental Progs',
'Interdisciplinary Informatics': 'Interdisciplinary Informatics',
'Interdisciplinary Programs': 'Interdisciplinary Programs',
'Internal Medicine': 'Internal Medicine',
'International Writing': 'International Writing',
'International Writing Program': 'International Writing Program',
'Iowa Lakeside Laboratory': 'Iowa Lakeside Laboratory',
'Iowa Law Review Balance': 'Iowa Law Review Balance',
'Iowa Nonprofit Resource Center': 'Iowa Nonprofit Resource Center',
'Iowa Testing Programs': 'Iowa Testing Programs',
'IPA - Publications': 'IPA - Publications',
'JMPEC - Des Moines': 'JMPEC - Des Moines',
'Journalism and Mass Communic': 'Journalism and Mass Communic',
'Labor Center': 'Labor Center',
'Language Media Center': 'Language Media Center',
'Law Cont Legal Education': 'Law Cont Legal Education',
'Law Faculty': 'Law Faculty',
'Law Hp and Disability Cntr': 'Law Hp and Disability Cntr',
'Law Library': 'Law Library',
'Law Student Aid': 'Law Student Aid',
'Law Student Services Programs': 'Law Student Services Programs',
'Law, Bus & Innovations Center': 'Law, Bus & Innovations Center',
'Learning Resource Center': 'Learning Resource Center',
'Liberal Arts and Science Admin': 'Liberal Arts and Science Admin',
'Linguistics': 'Linguistics',
'Management and Organizations': 'Management and Organizations',
'Management Sciences': 'Management Sciences',
'Marketing': 'Marketing',
'Mathematics': 'Mathematics',
'Mechanical Engineering': 'Mechanical Engineering',
'Medical Audiovisual': 'Medical Audiovisual',
'Medical Ethics': 'Medical Ethics',
'Medical Instrument Shop': 'Medical Instrument Shop',
'Medicinal Natural Products': 'Medicinal Natural Products',
'Medicine Administration': 'Medicine Administration',
'Microbiology': 'Microbiology',
'Military Science': 'Military Science',
'Museum Of Natural History': 'Museum Of Natural History',
'Music': 'Music',
'Nads and Simulation Center': 'Nads and Simulation Center',
'Neurology': 'Neurology',
'Neurosurgery': 'Neurosurgery',
'Nursing': 'Nursing',
'Nursing Administration and Gen': 'Nursing Administration and Gen',
'Obermann Center Advan Studies': 'Obermann Center Advan Studies',
'OBGyn': 'OBGyn',
'Occupational Environment Hlth': 'Occupational Environment Hlth',
'Office Of Animal Resources': 'Office Of Animal Resources',
'Office Of Mgmt and Bus Dev': 'Office Of Mgmt and Bus Dev',
'Office Of Student Services Edu': 'Office Of Student Services Edu',
'Office of the IACUC': 'Office of the IACUC',
'OITC': 'OITC',
'Operative Dentistry': 'Operative Dentistry',
'Ophthalmology and Visual Sci': 'Ophthalmology and Visual Sci',
'Optical Science Tech Ctr OSTC': 'Optical Science Tech Ctr OSTC',
'Oral and Maxillofacial Surgery': 'Oral and Maxillofacial Surgery',
'Oral Path Radiology Medicine': 'Oral Path Radiology Medicine',
'Organization Sys and Community': 'Organization Sys and Community',
'Orthodontics': 'Orthodontics',
'Orthopaedic Surgery': 'Orthopaedic Surgery',
'Otolaryngology Head Neck Surg': 'Otolaryngology Head Neck Surg',
'Pappajohn Biomedical Res Inst': 'Pappajohn Biomedical Res Inst',
'Parent Child and Family': 'Parent Child and Family',
'Pathology': 'Pathology',
'Pediatric Dentistry': 'Pediatric Dentistry',
'Pediatrics': 'Pediatrics',
'Pentacrest Museums': 'Pentacrest Museums',
'Periodontics': 'Periodontics',
'Pharmaceutics': 'Pharmaceutics',
'Pharmacology': 'Pharmacology',
'Pharmacy': 'Pharmacy',
'Pharmacy Practice and Science': 'Pharmacy Practice and Science',
'Philosophy': 'Philosophy',
'Physical Ther & Rehab Science': 'Physical Ther & Rehab Science',
'Physician Assistant': 'Physician Assistant',
'Physics and Astronomy': 'Physics and Astronomy',
'Physiology': 'Physiology',
'Political Science': 'Political Science',
'Ponseti International': 'Ponseti International',
'Preventive and Community Dent': 'Preventive and Community Dent',
'Production': 'Production',
'Prosthodontics': 'Prosthodontics',
'PSET': 'PSET',
'Psych and Quant Foundations': 'Psych and Quant Foundations',
'Psychiatry': 'Psychiatry',
'Psychology': 'Psychology',
'Public Health Administration': 'Public Health Administration',
'Public Health Genetics': 'Public Health Genetics',
'Public Policy Center': 'Public Policy Center',
'Radiation Oncology': 'Radiation Oncology',
'Radiation Research Laboratory': 'Radiation Research Laboratory',
'Radiology': 'Radiology',
'Rehabilitation & Counselor Ed': 'Rehabilitation & Counselor Ed',
'Religious Studies': 'Religious Studies',
'Research Administration': 'Research Administration',
'Research Dept': 'Research Dept',
'Research Information Syst Ris': 'Research Information Syst Ris',
'Research Services Admin': 'Research Services Admin',
'Rhetoric': 'Rhetoric',
'School Library Info Science': 'School Library Info Science',
'Social Work': 'Social Work',
'Sociology': 'Sociology',
'Spanish and Portuguese': 'Spanish and Portuguese',
'State Archaeologist': 'State Archaeologist',
'Statewide Residency Train Prog': 'Statewide Residency Train Prog',
'Statistics Actuarial Science': 'Statistics Actuarial Science',
'Stead Center': 'Stead Center',
'Stead Technology Service Group': 'Stead Technology Service Group',
'Study Abroad': 'Study Abroad',
'Surgery': 'Surgery',
'Systems and Practice': 'Systems and Practice',
'Teaching and Learning': 'Teaching and Learning',
'Theatre Arts': 'Theatre Arts',
'U of IA Center for Conferences': 'U of IA Center for Conferences',
'UI Center for Human Rights': 'UI Center for Human Rights',
'UI Pharm Drug Development': 'UI Pharm Drug Development',
'UI Pharmaceutical': 'UI Pharmaceutical',
'UI Press Office Operations': 'UI Press Office Operations',
'University College Courses': 'University College Courses',
'University Employee Hlth Clin': 'University Employee Hlth Clin',
'University Placement Center': 'University Placement Center',
'Urban and Regional Planning': 'Urban and Regional Planning',
'Urology': 'Urology',
'VP Research Biosciences': 'VP Research Biosciences',
'Women Science and Engineering': 'Women Science and Engineering',
'Writing Program': 'Writing Program',
'Other': 'Other',
'Not UI Personnel': 'Not UI Personnel'
}
replace 'subject_ethnicities', with: SUBJECT_ETHNICITIES
replace 'subject_genders', with: SUBJECT_GENDERS

replace 'colleges', with: COLLEGES

replace 'departments', with: DEPARTMENTS
