default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

production:
  <<: *default
  database: {{cfg.database_name}}
  username: {{cfg.database_username}}
  password: {{cfg.database_password}}
{{#if bind.has_database}}
{{#each bind.database.members as |member|}}
  host: {{member.sys.ip}}
  port: {{member.cfg.port}}
{{/each}}
{{else}}
  host: {{cfg.database_host}}
  port: {{cfg.database_port}}
{{/if}}
