#!/bin/sh

. /hab/svc/sparc-request/config/dotenv

cd $SERVICE_DIR/release

exec 2>&1

exec $SERVICE_DIR/release/bin/delayed_job run \
  --pid-dir {{pkg.svc_var_path}} \
  --log-dir {{pkg.svc_path}}/logs
