#!/bin/sh
export SERVICE_DIR="/hab/svc/sparc-request/static"

export GEM_HOME="${SERVICE_DIR}/release/vendor/bundle/ruby/2.1.0"
export GEM_PATH="{{pkgPathFor "chrisortman/ruby"}}/lib/ruby/gems/2.1.0:$GEM_HOME"
export LD_LIBRARY_PATH="{{pkgPathFor "core/gcc-libs"}}/lib"

export PATH="${SERVICE_DIR}/release/bin:$PATH"

export RAILS_ENV="production"

cd $SERVICE_DIR/release

exec 2>&1

# I think if i dont' fully qualify this I will get bin/passenger and I don't want that. It's because of the order of my PATH up above... I could probably change that I guess

exec $SERVICE_DIR/release/script/delayed_job run


#exec chpst -u hab ./bin/rails server -b {{cfg.rails_binding_ip}} -p {{cfg.rails_port}}
