#!/bin/sh

. /hab/svc/sparc-request/config/dotenv

export RACK_ENV=$RAILS_ENV
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
cd $SERVICE_DIR/release

{{#if bind.base.first}}
  {{#with bind.base.first as |base|}}
PORT='{{base.cfg.rails-port}}'
  {{/with}}
{{else}}
PORT='9292'
{{/if}}

exec 2>&1

exec bin/puma -e $RAILS_ENV -p $PORT
