#!/bin/sh

. /hab/svc/sparc-request/config/dotenv

cd $SERVICE_DIR/release

exec 2>&1

exec bin/puma start -e $RAILS_ENV \
{{#if bind.base.first}}
  {{#with bind.base.first as |base|}}
  -p {{base.cfg.rails-port}}
  {{/with}}
{{else}}
  -p 9292
{{/if}}
