#!/bin/sh

set -o nounset
set -e

. {{pkg.svc_config_path}}/dotenv

echo "Creating symlinked directories"
mkdir -pv {{pkg.svc_var_path}}/log
mkdir -pv {{pkg.svc_var_path}}/tmp
mkdir -pv {{pkg.svc_var_path}}/tmp/pids
mkdir -pv {{pkg.svc_data_path}}/system
chmod 775 {{pkg.svc_data_path}}/system

# Need these permissions to make apache happy
# and let it serve our static stuff
# chmod +rx ${SERVICE_DIR}/release/public
# chmod +rx ${SERVICE_DIR}/release
# chmod +rx ${SERVICE_DIR}
chmod +rx {{pkg.svc_data_path}}

cd $RAILS_ROOT

if [[ -e {{pkg.svc_data_path}}/migrate ]]; then
  echo "Running bootstrap task to initialize database"

  bin/rake sparc:bootstrap
  echo "Running database data upgrades"
  export HOME={{pkg.svc_data_path}}
  script/upgrade/3_0_0a-upgrade.sh
  rm {{pkg.svc_data_path}}/migrate
fi

