#!/bin/sh
export SPARC_DATA="{{pkg.svc_data_path}}"
export GEM_HOME="${SPARC_DATA}/dist/vendor/bundle/ruby/2.1.0"
export GEM_PATH="$(hab pkg path chrisortman/ruby)/lib/ruby/gems/2.1.0:$GEM_HOME"
export LD_LIBRARY_PATH="$(hab pkg path core/gcc-libs)/lib"
export PATH="$PATH:${SPARC_DATA}/dist/bin"
export RAILS_ENV="production"

cd $SPARC_DATA/dist

exec 2>&1
exec bin/rails server -b {{cfg.rails_binding_ip}} -p {{cfg.rails_port}}
#exec chpst -u hab ./bin/rails server -b {{cfg.rails_binding_ip}} -p {{cfg.rails_port}}
